{
  "configuration": {
    "environments": [
      {
        "source": "github",
        "service": "pusher",
        "destination": "dev"
      },
      {
        "source": "gitlab",
        "service": "syncer",
        "destination": "prod"
      }
    ]
  }
}
